export const state = {
  data: [
    {
      id: 0,
      type: false,
      label: 'Bón lót',
      plan: 'Kế hoạch trồng cải - Nhà màng 01',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Trễ 2 ngày',
      workGroupList: [
        {
          id: 1,
          name: 'Chuẩn bị vật tư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 2,
          name: 'Đo PH đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 3,
          name: 'Rải vôi',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 4,
          name: 'Gom tàn dư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 5,
          name: 'Cày phá đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 6,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 7,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 8,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 9,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 10,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 11,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
      ],
    },
    {
      id: 1,
      type: false,
      label: 'Bón thúc',
      plan: 'Kế hoạch trồng cải - Nhà màng 02',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Trễ 2 ngày',
      workGroupList: [
        {
          id: 1,
          name: 'Chuẩn bị vật tư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 2,
          name: 'Đo PH đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 3,
          name: 'Rải vôi',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 4,
          name: 'Gom tàn dư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 5,
          name: 'Cày phá đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 6,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 7,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 8,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 9,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 10,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 11,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
      ],
    },
    {
      id: 2,
      type: false,
      label: 'Gieo giống',
      plan: 'Kế hoạch trồng rau - Nhà màng 03',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Còn 2 ngày',
      workGroupList: [
        {
          id: 1,
          name: 'Chuẩn bị vật tư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 2,
          name: 'Đo PH đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 3,
          name: 'Rải vôi',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 4,
          name: 'Gom tàn dư',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 5,
          name: 'Cày phá đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 6,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 7,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 8,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 9,
          name: 'Phơi đất',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 10,
          name: 'Đo lại độ PH',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
        {
          id: 11,
          name: 'Lên luống',
          check: false,
          isCollapse: true,
          isCheck: false,
        },
      ],
    },
    {
      id: 3,
      type: true,
      label: 'Bón lót',
      plan: 'Kế hoạch trồng ray - Nhà màng 01',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Còn 2 ngày',
    },
    {
      id: 4,
      type: true,
      label: 'Bón lót',
      plan: 'Kế hoạch trồng cải - Nhà màng 03',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Còn 2 ngày',
    },
    {
      id: 5,
      type: false,
      label: 'Gieo giống',
      plan: 'Kế hoạch trồng cải - Nhà màng 03',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Trễ 2 ngày',
    },
    {
      id: 6,
      type: true,
      label: 'Bón lót',
      plan: 'Kế hoạch trồng cải - Nhà màng 03',
      timeStart: 1665368295000,
      timeEnd: 1671502695000,
      deadline: 'Còn 2 ngày',
    },
  ],
};
